# Generated by Django 5.2.6 on 2025-10-14 04:30

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopingo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orginal_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shopingo.subcategory'),
        ),
    ]
