# Generated by Django 5.2.6 on 2025-10-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopingo', '0002_product_orginal_price_alter_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
