# Generated by Django 5.2.6 on 2025-10-14 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopingo', '0003_product_discount_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_percent',
        ),
    ]
