# Generated by Django 5.2.6 on 2025-10-14 12:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopingo', '0004_remove_product_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_details',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
