# Generated by Django 5.2.6 on 2025-10-14 13:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopingo', '0005_product_description_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='more_information',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
