# Generated by Django 5.2.6 on 2025-10-21 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_division'),
        ('shopingo', '0007_cart_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('discount_percent', models.PositiveIntegerField(blank=True, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, to='shopingo.product')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Shipping type or name (e.g., Standard, Express)', max_length=100)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum order amount for this rate', max_digits=10)),
                ('charge_amount', models.DecimalField(decimal_places=2, help_text='Shipping cost', max_digits=10)),
                ('estimated_days', models.PositiveIntegerField(default=3, help_text='Estimated delivery time in days')),
                ('active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.countryname')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.division')),
            ],
            options={
                'verbose_name': 'Shipping Charge',
                'verbose_name_plural': 'Shipping Charges',
                'ordering': ['country', 'division', 'charge_amount'],
            },
        ),
    ]
