# Generated by Django 5.2.6 on 2025-10-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopingo', '0008_coupon_shippingcharge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingcharge',
            old_name='name',
            new_name='Shipping_type_name',
        ),
    ]
