# Generated by Django 5.2.6 on 2025-10-22 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_district'),
        ('shopingo', '0009_rename_name_shippingcharge_shipping_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingcharge',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.district'),
        ),
    ]
