# Generated by Django 5.2.6 on 2025-10-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopingo', '0011_country_shippingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
