# Generated by Django 5.2.6 on 2025-10-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopingo', '0012_delete_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingcharge',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
