# Generated by Django 5.2.6 on 2025-10-28 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopingo', '0016_order_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size_color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopingo.cart'),
            preserve_default=False,
        ),
    ]
