# Generated by Django 5.2.6 on 2025-10-28 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopingo', '0017_remove_orderitem_color_remove_orderitem_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
