# Generated by Django 5.2.6 on 2025-11-14 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopingo', '0021_orderitem_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_orders', to='shopingo.cart')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='shopingo.order')),
                ('order_items', models.ManyToManyField(related_name='completed_orders', to='shopingo.orderitem')),
                ('shipping_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_orders', to='shopingo.shippingaddress')),
            ],
        ),
    ]
