# Generated by Django 5.2.6 on 2025-11-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopingo', '0022_completedorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedorder',
            name='customer_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completedorder',
            name='product_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
