# Generated by Django 5.2.6 on 2025-11-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopingo', '0024_order_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Order Confirmed'), ('picked', 'Picked by courier'), ('onway', 'On the way'), ('ready', 'Ready for pickup')], default='confirmed', max_length=20)),
            ],
        ),
    ]
