# Generated by Django 5.2.6 on 2025-11-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopingo', '0026_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='price_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
