# Generated by Django 5.2.6 on 2025-11-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopingo', '0027_variation_price_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
