# Generated by Django 5.2.6 on 2025-11-22 13:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopingo', '0028_product_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address_line', models.TextField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('working_day_start', models.TimeField(blank=True, null=True)),
                ('working_day_end', models.TimeField(blank=True, null=True)),
                ('working_time_start', models.TimeField(blank=True, null=True)),
                ('working_time_end', models.TimeField(blank=True, null=True)),
                ('our_story', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='why_choose_us/')),
                ('icon_file', models.CharField(blank=True, help_text='Example: delivery.png, money-bag.png, support.png', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/'),
        ),
    ]
