"""
Matched catalog blueprint for seed_catalog.

Every product includes unique title, brand, type-matched image tags,
and a short description that describes THAT product.
"""


def _p(title, brand, regular, sale, short, tags):
    return {
        "title": title,
        "brand": brand,
        "regular": regular,
        "sale": sale,
        "short": short,
        "tags": tags,
    }


CATALOG = [
    {
        "name": "Electronics",
        "icon": "bx-devices",
        "folder": "electronics",
        "promo_title": "Up to 40% Off Electronics",
        "promo_text": "Phones, laptops, headphones, watches and cameras from top brands.",
        "description": "Shop smartphones, laptops, headphones, smart watches and cameras.",
        "subs": [
            {
                "name": "Smartphones",
                "products": [
                    _p("Apple iPhone 16 Pro Max 256GB", "Apple", 1299, 1199,
                       "Flagship Apple smartphone with A18 Pro chip, ProMotion OLED and triple 48MP camera.",
                       "smartphone,iphone,apple,mobile"),
                    _p("Samsung Galaxy S25 Ultra 512GB", "Samsung", 1399, 1249,
                       "Premium Samsung Android phone with S Pen, 200MP camera and Dynamic AMOLED display.",
                       "smartphone,samsung,android,galaxy"),
                    _p("Google Pixel 10 Pro 256GB", "Google", 999, 899,
                       "Google Pixel with advanced computational photography and clean Android experience.",
                       "smartphone,google,pixel,android"),
                    _p("OnePlus 13 256GB", "OnePlus", 899, 799,
                       "Fast OnePlus flagship with Hasselblad-tuned cameras and rapid charging.",
                       "smartphone,oneplus,android,phone"),
                    _p("Xiaomi 15 Ultra 512GB", "Xiaomi", 1099, 949,
                       "Xiaomi imaging flagship with large sensor camera system and high-refresh AMOLED.",
                       "smartphone,xiaomi,android,mobile"),
                    _p("Nothing Phone 3 256GB", "Nothing", 749, 679,
                       "Distinctive Nothing Phone with Glyph interface and transparent design language.",
                       "smartphone,nothing,android,phone"),
                    _p("Vivo X300 Pro 256GB", "Vivo", 899, 819,
                       "Vivo camera-focused smartphone with portrait optics and smooth AMOLED screen.",
                       "smartphone,vivo,android,mobile"),
                    _p("Oppo Find X9 256GB", "Oppo", 999, 879,
                       "Oppo Find series phone with slim build, fast charge and versatile camera.",
                       "smartphone,oppo,android,phone"),
                    _p("Motorola Edge 60 Pro", "Motorola", 799, 699,
                       "Motorola Edge with clean Android, curved display and reliable all-day battery.",
                       "smartphone,motorola,android,mobile"),
                    _p("Realme GT 8 256GB", "Realme", 649, 579,
                       "Performance-oriented Realme GT phone for gaming and everyday speed.",
                       "smartphone,realme,android,phone"),
                    _p("Honor Magic 8 Pro", "Honor", 899, 799,
                       "Honor Magic series smartphone with AI features and premium glass design.",
                       "smartphone,honor,android,mobile"),
                    _p("Asus ROG Phone 10", "Asus", 1199, 1049,
                       "Asus ROG gaming smartphone with high refresh rate display and advanced cooling.",
                       "smartphone,gaming,asus,android"),
                ],
            },
            {
                "name": "Laptops",
                "products": [
                    _p("Apple MacBook Air 13 M4", "Apple", 1299, 1199,
                       "Ultra-light MacBook Air with Apple M4 chip, Liquid Retina display and all-day battery.",
                       "laptop,macbook,apple,notebook"),
                    _p("Dell XPS 14 OLED", "Dell", 1499, 1349,
                       "Dell XPS ultraportable with vivid OLED panel and premium CNC aluminum chassis.",
                       "laptop,dell,xps,notebook"),
                    _p("Lenovo ThinkPad X1 Carbon", "Lenovo", 1599, 1449,
                       "Business ThinkPad with legendary keyboard, light carbon body and enterprise security.",
                       "laptop,lenovo,thinkpad,notebook"),
                    _p("HP Spectre x360 14", "HP", 1399, 1249,
                       "Convertible HP Spectre with 360-degree hinge, stylus support and elegant design.",
                       "laptop,hp,spectre,notebook"),
                    _p("Asus ZenBook 14 OLED", "Asus", 1199, 1049,
                       "Slim Asus ZenBook with OLED display, NumberPad and long battery life.",
                       "laptop,asus,zenbook,notebook"),
                    _p("Acer Swift Go 14", "Acer", 899, 799,
                       "Lightweight Acer Swift Go for students and professionals on the move.",
                       "laptop,acer,swift,notebook"),
                    _p("MSI Stealth 16 Gaming", "MSI", 1799, 1599,
                       "Thin MSI Stealth gaming laptop with discrete GPU and high-refresh display.",
                       "laptop,msi,gaming,notebook"),
                    _p("Razer Blade 16", "Razer", 2499, 2299,
                       "Premium Razer Blade gaming notebook with CNC aluminum body and powerful GPU.",
                       "laptop,razer,gaming,notebook"),
                    _p("Samsung Galaxy Book4 Pro", "Samsung", 1299, 1149,
                       "Samsung Galaxy Book with AMOLED screen and seamless Galaxy ecosystem sync.",
                       "laptop,samsung,notebook,ultrabook"),
                    _p("LG Gram 16", "LG", 1399, 1249,
                       "Featherlight LG Gram 16-inch laptop with large screen and excellent battery.",
                       "laptop,lg,gram,notebook"),
                    _p("Microsoft Surface Laptop 7", "Microsoft", 1299, 1179,
                       "Surface Laptop with touchscreen, refined build and Windows Copilot-plus features.",
                       "laptop,microsoft,surface,notebook"),
                    _p("Huawei MateBook X Pro", "Huawei", 1199, 1049,
                       "Huawei MateBook ultraportable with sharp display and compact charger.",
                       "laptop,huawei,matebook,notebook"),
                ],
            },
            {
                "name": "Headphones",
                "products": [
                    _p("Sony WH-1000XM6 Wireless", "Sony", 449, 399,
                       "Industry-leading Sony noise-cancelling over-ear headphones with rich sound.",
                       "headphones,sony,wireless,audio"),
                    _p("Apple AirPods Pro 3", "Apple", 279, 249,
                       "Apple AirPods Pro with active noise cancellation, Adaptive Audio and MagSafe case.",
                       "earbuds,airpods,apple,wireless"),
                    _p("Bose QuietComfort Ultra", "Bose", 429, 379,
                       "Bose QuietComfort Ultra headphones with immersive audio and premium ANC.",
                       "headphones,bose,noise-cancelling,wireless"),
                    _p("JBL Flip 7 Bluetooth Speaker", "JBL", 149, 129,
                       "Portable JBL Flip speaker with bold bass and waterproof design.",
                       "speaker,jbl,bluetooth,portable"),
                    _p("Sennheiser Momentum 4", "Sennheiser", 379, 329,
                       "Sennheiser Momentum 4 wireless headphones with audiophile tuning and long battery.",
                       "headphones,sennheiser,wireless,audio"),
                    _p("Samsung Galaxy Buds 3 Pro", "Samsung", 249, 219,
                       "Samsung Galaxy Buds with ANC, 360 audio and seamless Galaxy pairing.",
                       "earbuds,samsung,wireless,galaxy"),
                    _p("Nothing Ear 3", "Nothing", 149, 129,
                       "Nothing Ear true wireless earbuds with transparent case and clear calls.",
                       "earbuds,nothing,wireless,headphones"),
                    _p("Anker Soundcore Liberty 4", "Anker", 129, 99,
                       "Anker Soundcore Liberty earbuds with strong battery and app EQ controls.",
                       "earbuds,anker,soundcore,wireless"),
                    _p("Marshall Emberton III", "Marshall", 169, 149,
                       "Marshall Emberton portable speaker with signature rock sound and rugged shell.",
                       "speaker,marshall,bluetooth,portable"),
                    _p("Beats Studio Pro", "Beats", 349, 299,
                       "Beats Studio Pro over-ears with spatial audio and customizable ANC.",
                       "headphones,beats,wireless,audio"),
                    _p("Audio-Technica ATH-M50x", "Audio-Technica", 169, 149,
                       "Audio-Technica ATH-M50x studio monitor headphones trusted by creators for accurate sound.",
                       "headphones,studio,audio-technica,wired"),
                    _p("Sony WF-1000XM5 Earbuds", "Sony", 299, 259,
                       "Compact Sony XM5 earbuds with excellent noise cancellation and LDAC audio.",
                       "earbuds,sony,wireless,headphones"),
                ],
            },
            {
                "name": "Smart Watches",
                "products": [
                    _p("Apple Watch Ultra 3", "Apple", 799, 749,
                       "Rugged Apple Watch Ultra for athletes with precision GPS and bright display.",
                       "smartwatch,apple,watch,wearable"),
                    _p("Samsung Galaxy Watch 7", "Samsung", 349, 299,
                       "Samsung Galaxy Watch with Wear OS, health sensors and rotating bezel.",
                       "smartwatch,samsung,galaxy,wearable"),
                    _p("Garmin Fenix 8 Sapphire", "Garmin", 999, 899,
                       "Garmin Fenix multisport GPS watch with maps and tough build.",
                       "smartwatch,garmin,sports,watch"),
                    _p("Fitbit Charge 7", "Fitbit", 179, 149,
                       "Fitbit Charge fitness band with heart-rate tracking and sleep insights.",
                       "fitness,fitbit,tracker,wearable"),
                    _p("Amazfit Balance Watch", "Amazfit", 229, 199,
                       "Amazfit Balance smartwatch with dual-band GPS and long battery life.",
                       "smartwatch,amazfit,fitness,wearable"),
                    _p("Huawei Watch GT 5 Pro", "Huawei", 299, 259,
                       "Huawei Watch GT with elegant design, SpO2 monitoring and multi-day battery.",
                       "smartwatch,huawei,watch,wearable"),
                    _p("OnePlus Watch 3", "OnePlus", 199, 169,
                       "OnePlus Watch with dual-engine battery mode and clear always-on display.",
                       "smartwatch,oneplus,watch,wearable"),
                    _p("Xiaomi Watch S4", "Xiaomi", 149, 129,
                       "Xiaomi smartwatch with AMOLED screen, GPS and comprehensive sport modes.",
                       "smartwatch,xiaomi,watch,wearable"),
                    _p("Noise ColorFit Pro 6", "Noise", 89, 69,
                       "Affordable Noise ColorFit smartwatch with SpO2 and Bluetooth calling.",
                       "smartwatch,noise,fitness,wearable"),
                    _p("Fire-Boltt Invincible Plus", "Fire-Boltt", 99, 79,
                       "Fire-Boltt smartwatch with large display and multiple sports tracking modes.",
                       "smartwatch,fireboltt,fitness,wearable"),
                    _p("Titan Smart Pro Hybrid", "Titan", 159, 139,
                       "Titan hybrid smartwatch blending classic dial style with smart notifications.",
                       "smartwatch,titan,watch,wearable"),
                    _p("Casio G-Shock GBD-H2000", "Casio", 349, 299,
                       "Casio G-Shock tough smartwatch with heart rate, GPS and shock resistance.",
                       "smartwatch,casio,gshock,sports"),
                ],
            },
            {
                "name": "Cameras",
                "products": [
                    _p("Canon EOS R6 Mark II Body", "Canon", 2499, 2299,
                       "Full-frame Canon mirrorless camera for photo and 4K video creators.",
                       "camera,canon,mirrorless,photography"),
                    _p("Sony Alpha a7 IV Body", "Sony", 2499, 2299,
                       "Sony full-frame hybrid camera with excellent autofocus and 4K60 video.",
                       "camera,sony,mirrorless,photography"),
                    _p("Nikon Z6 III Body", "Nikon", 2499, 2299,
                       "Nikon Z6 III mirrorless with partially stacked sensor and pro video tools.",
                       "camera,nikon,mirrorless,photography"),
                    _p("Fujifilm X-T5 Body", "Fujifilm", 1699, 1549,
                       "Fujifilm X-T5 APS-C camera with classic dials and outstanding color science.",
                       "camera,fujifilm,mirrorless,photography"),
                    _p("GoPro HERO13 Black", "GoPro", 449, 399,
                       "GoPro action camera with HyperSmooth video and rugged waterproof design.",
                       "gopro,action-camera,camera,sports"),
                    _p("DJI Osmo Pocket 3", "DJI", 519, 469,
                       "DJI Pocket 3 compact gimbal camera for stabilized vlog-ready footage.",
                       "camera,dji,gimbal,vlog"),
                    _p("Canon PowerShot G7 X III", "Canon", 749, 679,
                       "Compact Canon vlogging camera with flip screen and 4K recording.",
                       "camera,canon,compact,vlog"),
                    _p("Sony ZV-E10 II Body", "Sony", 999, 899,
                       "Sony creator camera optimized for vlogging with product showcase setting.",
                       "camera,sony,vlog,mirrorless"),
                    _p("Insta360 X4 360 Camera", "Insta360", 529, 479,
                       "Insta360 X4 dual-lens 360 camera for immersive adventure footage.",
                       "camera,insta360,360,action"),
                    _p("Panasonic Lumix S5 II", "Panasonic", 1999, 1799,
                       "Panasonic Lumix full-frame hybrid with phase-detect AF and strong video.",
                       "camera,panasonic,lumix,mirrorless"),
                    _p("Olympus OM System OM-5", "OM System", 1199, 1099,
                       "Weather-sealed OM-5 travel camera with in-body stabilization and compact body.",
                       "camera,olympus,mirrorless,travel"),
                    _p("Leica D-Lux 8 Compact", "Leica", 1599, 1499,
                       "Premium Leica compact camera with exceptional optics and classic styling.",
                       "camera,leica,compact,photography"),
                ],
            },
        ],
    },
    {
        "name": "Fashion",
        "icon": "bx-t-shirt",
        "folder": "fashion",
        "promo_title": "New Season Fashion",
        "promo_text": "Clothing, shoes, bags and watches for every style.",
        "description": "Shop men's and women's clothing, shoes, bags and watches.",
        "subs": [
            {
                "name": "Men's Clothing",
                "products": [
                    _p("Ralph Lauren Classic Oxford Shirt", "Ralph Lauren", 129, 99,
                       "Crisp men's oxford cotton shirt with button-down collar for smart casual wear.",
                       "shirt,men,oxford,clothing"),
                    _p("Levi's 511 Slim Fit Jeans", "Levi's", 89, 69,
                       "Men's slim-fit denim jeans with classic 511 cut and durable stretch fabric.",
                       "jeans,men,denim,levis"),
                    _p("Nike Dri-FIT Training Tee", "Nike", 45, 35,
                       "Breathable Nike Dri-FIT men's training t-shirt for workouts and everyday wear.",
                       "tshirt,nike,men,athletic"),
                    _p("Tommy Hilfiger Wool Blazer", "Tommy Hilfiger", 249, 199,
                       "Tailored men's wool-blend blazer for office and evening occasions.",
                       "blazer,men,suit,formal"),
                    _p("The North Face Denim Jacket", "The North Face", 149, 119,
                       "Rugged men's denim jacket with comfortable fit for cooler weather.",
                       "jacket,denim,men,clothing"),
                    _p("Adidas Essentials Cargo Pants", "Adidas", 75, 59,
                       "Men's cargo pants with practical pockets and relaxed everyday comfort.",
                       "pants,men,cargo,adidas"),
                    _p("Uniqlo Merino Crew Sweater", "Uniqlo", 59, 45,
                       "Soft merino wool crewneck sweater for men with lightweight warmth.",
                       "sweater,men,wool,clothing"),
                    _p("Polo Ralph Lauren Performance Polo", "Polo Ralph Lauren", 89, 69,
                       "Moisture-wicking men's polo shirt with classic embroidered logo.",
                       "polo,men,shirt,ralphlauren"),
                    _p("H&M Linen Summer Shirt", "H&M", 39, 29,
                       "Breathable men's linen shirt ideal for warm weather and vacation looks.",
                       "shirt,linen,men,summer"),
                    _p("Zara Tailored Suit Trousers", "Zara", 69, 55,
                       "Slim tailored men's suit trousers for business and formal styling.",
                       "trousers,men,suit,formal"),
                    _p("Champion Reverse Weave Hoodie", "Champion", 79, 59,
                       "Heavyweight men's hoodie with iconic reverse weave construction.",
                       "hoodie,men,champion,sweatshirt"),
                    _p("Columbia Quilted Bomber Jacket", "Columbia", 129, 99,
                       "Insulated men's bomber jacket for outdoor comfort in chilly weather.",
                       "jacket,bomber,men,outdoor"),
                ],
            },
            {
                "name": "Women's Clothing",
                "products": [
                    _p("Zara Floral Midi Dress", "Zara", 79, 59,
                       "Elegant women's floral midi dress with flattering silhouette.",
                       "dress,women,floral,fashion"),
                    _p("Levi's High-Rise Skinny Jeans", "Levi's", 89, 69,
                       "Women's high-rise skinny jeans with stretch denim and sleek fit.",
                       "jeans,women,denim,levis"),
                    _p("Mango Silk Blend Blouse", "Mango", 69, 55,
                       "Soft silk-blend women's blouse with refined drape for office and brunch.",
                       "blouse,women,silk,fashion"),
                    _p("H&M Knit Cardigan Soft", "H&M", 45, 35,
                       "Cozy women's knit cardigan for layering over dresses and tees.",
                       "cardigan,women,knit,fashion"),
                    _p("Uniqlo A-Line Summer Skirt", "Uniqlo", 39, 29,
                       "Lightweight A-line skirt with comfortable elastic waist for warm days.",
                       "skirt,women,summer,fashion"),
                    _p("Calvin Klein Office Sheath Dress", "Calvin Klein", 129, 99,
                       "Polished sheath dress for women with clean lines for professional settings.",
                       "dress,women,office,formal"),
                    _p("Levi's Cropped Denim Jacket", "Levi's", 98, 78,
                       "Women's cropped denim jacket for casual layering across seasons.",
                       "jacket,denim,women,fashion"),
                    _p("Nike One Luxe Leggings", "Nike", 65, 49,
                       "High-waisted Nike training leggings with supportive fit and soft stretch.",
                       "leggings,nike,women,athletic"),
                    _p("Mango Wrap Maxi Dress", "Mango", 89, 69,
                       "Flowy wrap maxi dress with adjustable tie waist for versatile styling.",
                       "dress,women,maxi,fashion"),
                    _p("Uniqlo Cashmere Mix Sweater", "Uniqlo", 79, 59,
                       "Luxuriously soft cashmere-mix sweater for women in a relaxed fit.",
                       "sweater,women,cashmere,fashion"),
                    _p("Zara Pleated Palazzo Pants", "Zara", 59, 45,
                       "Wide-leg pleated palazzo pants that elevate casual and dressy looks.",
                       "pants,women,palazzo,fashion"),
                    _p("FabIndia Embroidered Kurti Set", "FabIndia", 69, 55,
                       "Handcrafted embroidered kurti set with elegant ethnic detailing.",
                       "kurti,women,ethnic,fashion"),
                ],
            },
            {
                "name": "Shoes",
                "products": [
                    _p("Nike Air Max Runner", "Nike", 149, 119,
                       "Nike Air Max running sneakers with visible Air cushioning and breathable upper.",
                       "sneakers,nike,shoes,running"),
                    _p("Adidas Ultraboost Light", "Adidas", 189, 159,
                       "Adidas Ultraboost Light shoes with responsive Boost foam for daily runs.",
                       "sneakers,adidas,shoes,running"),
                    _p("Adidas Stan Smith Classic", "Adidas", 110, 89,
                       "Iconic Stan Smith leather sneakers with clean white court style.",
                       "sneakers,adidas,shoes,white"),
                    _p("Clarks Chelsea Boot Urban", "Clarks", 159, 129,
                       "Men's Chelsea boots with elastic side panels and durable leather finish.",
                       "boots,chelsea,shoes,leather"),
                    _p("Cole Haan Oxford Formal Shoe", "Cole Haan", 198, 169,
                       "Polished oxford dress shoes for formal events and business attire.",
                       "oxford,shoes,formal,leather"),
                    _p("Merrell Trail Hiking Boot", "Merrell", 149, 119,
                       "Trail hiking boots with grippy outsole and waterproof protection.",
                       "boots,hiking,shoes,outdoor"),
                    _p("Vionic Ballet Flat Comfort", "Vionic", 99, 79,
                       "Supportive ballet flats designed for all-day comfort and style.",
                       "flats,shoes,women,ballet"),
                    _p("New Balance 574 Chunky Sneaker", "New Balance", 110, 89,
                       "Classic New Balance 574 sneakers with retro chunky silhouette.",
                       "sneakers,newbalance,shoes,casual"),
                    _p("Vans Classic Slip-On", "Vans", 70, 55,
                       "Vans slip-on canvas sneakers with signature waffle outsole.",
                       "sneakers,vans,shoes,canvas"),
                    _p("Steve Madden Heeled Sandal", "Steve Madden", 89, 69,
                       "Women's heeled sandals for evening outfits and summer occasions.",
                       "sandals,heels,shoes,women"),
                    _p("Nike Calm Slide Sandals", "Nike", 45, 35,
                       "Soft Nike slide sandals for poolside, gym bag and casual wear.",
                       "slides,nike,sandals,shoes"),
                    _p("Aldo Premium Leather Loafer", "Aldo", 129, 99,
                       "Premium leather loafers with bit detail for smart-casual outfits.",
                       "loafers,shoes,leather,formal"),
                ],
            },
            {
                "name": "Bags",
                "products": [
                    _p("Coach Leather Tote Classic", "Coach", 349, 299,
                       "Spacious Coach leather tote for work, travel and everyday essentials.",
                       "tote,bag,leather,handbag"),
                    _p("Michael Kors Crossbody Mini", "Michael Kors", 198, 169,
                       "Compact crossbody bag with adjustable strap and signature hardware.",
                       "crossbody,bag,handbag,women"),
                    _p("Samsonite Laptop Backpack Pro", "Samsonite", 129, 99,
                       "Padded laptop backpack with multiple organizers for commuting.",
                       "backpack,laptop,bag,samsonite"),
                    _p("Herschel Weekend Duffle", "Herschel", 99, 79,
                       "Weekend duffle bag with durable fabric and roomy main compartment.",
                       "duffle,bag,travel,herschel"),
                    _p("Kate Spade Quilted Shoulder Bag", "Kate Spade", 278, 229,
                       "Quilted shoulder bag with chain strap for polished everyday looks.",
                       "handbag,quilted,bag,women"),
                    _p("Fjallraven Canvas Messenger", "Fjallraven", 149, 119,
                       "Canvas messenger bag with weather-resistant fabric and flap closure.",
                       "messenger,bag,canvas,fjallraven"),
                    _p("Peak Design Everyday Sling", "Peak Design", 119, 99,
                       "Camera-friendly sling bag with flexible dividers for gear on the go.",
                       "sling,bag,camera,peakdesign"),
                    _p("Tory Burch Structured Handbag", "Tory Burch", 398, 349,
                       "Structured handbag with elegant silhouette and secure top handle.",
                       "handbag,bag,women,toryburch"),
                    _p("Away Travel Cabin Trolley", "Away", 275, 229,
                       "Lightweight cabin trolley suitcase with 360-degree wheels.",
                       "suitcase,luggage,travel,away"),
                    _p("Lululemon Everywhere Belt Bag", "Lululemon", 48, 38,
                       "Popular belt bag for hands-free storage of phone, keys and cards.",
                       "beltbag,fannypack,bag,lululemon"),
                    _p("Longchamp Shopper Eco Tote", "Longchamp", 145, 119,
                       "Foldable nylon shopper tote that is lightweight and packable.",
                       "tote,shopper,bag,longchamp"),
                    _p("Fossil Wallet Clutch Set", "Fossil", 89, 69,
                       "Leather wallet clutch set for cards, cash and evening essentials.",
                       "wallet,clutch,bag,leather"),
                ],
            },
            {
                "name": "Watches",
                "products": [
                    _p("Casio Edifice Chronograph Steel", "Casio", 199, 159,
                       "Stainless chronograph watch with sporty Edifice design and date window.",
                       "watch,casio,chronograph,wristwatch"),
                    _p("Timex Weekender Minimalist", "Timex", 59, 45,
                       "Minimalist Timex Weekender with interchangeable strap options.",
                       "watch,timex,minimal,wristwatch"),
                    _p("Seiko 5 Sports Automatic", "Seiko", 299, 249,
                       "Reliable Seiko 5 automatic watch with day-date and hardlex crystal.",
                       "watch,seiko,automatic,wristwatch"),
                    _p("Fossil Grant Chronograph", "Fossil", 159, 129,
                       "Fossil Grant chronograph with leather strap and classic dial.",
                       "watch,fossil,chronograph,wristwatch"),
                    _p("Michael Kors Rose Gold Analog", "Michael Kors", 229, 189,
                       "Rose gold-tone analog watch designed for elegant everyday wear.",
                       "watch,michaelkors,rosegold,women"),
                    _p("Garmin Forerunner Sport Digital", "Garmin", 249, 219,
                       "GPS running watch with training metrics and smart notifications.",
                       "watch,garmin,sports,digital"),
                    _p("Daniel Wellington Dress Watch", "Daniel Wellington", 179, 149,
                       "Slim dress watch with clean dial and interchangeable straps.",
                       "watch,danielwellington,dress,minimal"),
                    _p("Orient Pilot Skeleton Automatic", "Orient", 349, 299,
                       "Open-heart skeleton automatic watch with pilot-inspired styling.",
                       "watch,orient,skeleton,automatic"),
                    _p("Timex Expedition Field Watch", "Timex", 89, 69,
                       "Rugged field watch with Indiglo night-light and durable case.",
                       "watch,timex,field,outdoor"),
                    _p("Anne Klein Pearl Dial Watch", "Anne Klein", 79, 59,
                       "Feminine pearl-dial watch with crystal markers and slim bracelet.",
                       "watch,anneklein,pearl,women"),
                    _p("Citizen Eco-Drive Pilot GMT", "Citizen", 399, 349,
                       "Citizen Eco-Drive GMT watch powered by light with dual time zones.",
                       "watch,citizen,gmt,pilot"),
                    _p("Fossil Leather Strap Classic", "Fossil", 129, 99,
                       "Classic analog watch with genuine leather strap and Roman markers.",
                       "watch,fossil,leather,classic"),
                ],
            },
        ],
    },
    {
        "name": "Home & Kitchen",
        "icon": "bx-home-alt",
        "folder": "home",
        "promo_title": "Upgrade Your Home",
        "promo_text": "Furniture, kitchen tools, decor, lighting and smart storage.",
        "description": "Shop furniture, kitchen essentials, home decor, lighting and storage.",
        "subs": [
            {
                "name": "Furniture",
                "products": [
                    _p("Sihoo Ergo Office Chair", "Sihoo", 349, 279,
                       "Ergonomic office chair with lumbar support and breathable mesh back.",
                       "chair,office,furniture,ergonomic"),
                    _p("West Elm Solid Wood Coffee Table", "West Elm", 399, 329,
                       "Solid wood coffee table with clean mid-century lines for living rooms.",
                       "table,coffee,furniture,wood"),
                    _p("IKEA Queen Bed Frame Oak", "IKEA", 299, 249,
                       "Queen-size oak bed frame with sturdy slats and modern minimalist look.",
                       "bed,furniture,bedroom,wood"),
                    _p("Article 3-Seater Fabric Sofa", "Article", 999, 849,
                       "Comfortable 3-seater fabric sofa with deep cushions and durable upholstery.",
                       "sofa,couch,furniture,livingroom"),
                    _p("Pottery Barn Study Desk Oak", "Pottery Barn", 449, 379,
                       "Oak study desk with spacious surface for work-from-home setups.",
                       "desk,furniture,office,wood"),
                    _p("IKEA Bookshelf 5-Tier", "IKEA", 129, 99,
                       "Five-tier bookshelf for books, plants and display decor.",
                       "bookshelf,furniture,storage,ikea"),
                    _p("Article Dining Set 4 Chairs", "Article", 799, 699,
                       "Dining table set with four matching chairs for everyday meals.",
                       "dining,table,furniture,chairs"),
                    _p("West Elm TV Unit Modern", "West Elm", 449, 379,
                       "Modern TV media unit with cable management and open shelving.",
                       "tvstand,furniture,media,livingroom"),
                    _p("IKEA Shoe Rack Slim", "IKEA", 49, 39,
                       "Slim shoe rack that organizes footwear in entryways and closets.",
                       "shoerack,furniture,storage,entryway"),
                    _p("Yogibo Bean Bag XL", "Yogibo", 229, 189,
                       "Extra-large bean bag chair that molds to your body for lounge comfort.",
                       "beanbag,furniture,lounge,chair"),
                    _p("IKEA Wardrobe 3-Door", "IKEA", 399, 329,
                       "Three-door wardrobe with hanging rail and shelves for bedroom storage.",
                       "wardrobe,furniture,bedroom,closet"),
                    _p("West Elm Nesting Side Tables", "West Elm", 249, 199,
                       "Set of nesting side tables in warm wood tones for flexible living spaces.",
                       "table,side,furniture,wood"),
                ],
            },
            {
                "name": "Kitchen",
                "products": [
                    _p("Ninja Air Fryer XL 5L", "Ninja", 149, 119,
                       "5L Ninja air fryer for crisp fries, wings and roasted veggies with less oil.",
                       "airfryer,kitchen,appliance,ninja"),
                    _p("Philips Mixer Grinder Pro", "Philips", 129, 99,
                       "Powerful mixer grinder with multiple jars for spices, chutneys and batters.",
                       "mixer,kitchen,appliance,grinder"),
                    _p("Prestige Induction Cooktop", "Prestige", 79, 59,
                       "Compact induction cooktop with preset menus and energy-efficient heating.",
                       "induction,cooktop,kitchen,appliance"),
                    _p("Breville Barista Espresso Machine", "Breville", 699, 599,
                       "Home espresso machine with integrated grinder for cafe-style coffee.",
                       "espresso,coffee,kitchen,breville"),
                    _p("KitchenAid Electric Kettle Steel", "KitchenAid", 89, 69,
                       "Brushed steel electric kettle with rapid boil and auto shut-off.",
                       "kettle,kitchen,appliance,steel"),
                    _p("Panasonic Microwave Convection", "Panasonic", 249, 199,
                       "Convection microwave for baking, grilling and everyday reheating.",
                       "microwave,kitchen,appliance,panasonic"),
                    _p("Braun Hand Blender Set", "Braun", 79, 59,
                       "Immersion hand blender set with whisk and chopper attachments.",
                       "blender,kitchen,appliance,braun"),
                    _p("Cuisinart Toaster 4-Slice", "Cuisinart", 69, 55,
                       "Four-slice toaster with bagel mode and shade control.",
                       "toaster,kitchen,appliance,cuisinart"),
                    _p("KitchenAid Food Processor Multi", "KitchenAid", 199, 169,
                       "Multi-function food processor for slicing, shredding and dough.",
                       "foodprocessor,kitchen,appliance,kitchenaid"),
                    _p("Zojirushi Rice Cooker Smart", "Zojirushi", 249, 209,
                       "Fuzzy-logic rice cooker for perfect fluffy rice every time.",
                       "ricecooker,kitchen,appliance,zojirushi"),
                    _p("George Foreman Sandwich Grill", "George Foreman", 49, 39,
                       "Compact sandwich and panini grill with non-stick plates.",
                       "grill,sandwich,kitchen,appliance"),
                    _p("Bosch Compact Dishwasher", "Bosch", 599, 529,
                       "Compact Bosch dishwasher with quiet wash cycles and efficient drying.",
                       "dishwasher,kitchen,appliance,bosch"),
                ],
            },
            {
                "name": "Home Decor",
                "products": [
                    _p("Abstract Wall Art Canvas Set", "Umbra", 89, 69,
                       "Set of abstract canvas prints to refresh living room or bedroom walls.",
                       "wallart,decor,canvas,home"),
                    _p("Ceramic Vase Duo Set", "West Elm", 59, 45,
                       "Pair of ceramic vases in complementary shapes for flowers or dried stems.",
                       "vase,ceramic,decor,home"),
                    _p("Yankee Candle Scented Trio", "Yankee Candle", 45, 35,
                       "Three popular scented jar candles for cozy ambiance at home.",
                       "candle,scented,decor,home"),
                    _p("Throw Pillow Pack of 4", "IKEA", 49, 39,
                       "Set of four decorative throw pillows in coordinating textures.",
                       "pillow,cushion,decor,sofa"),
                    _p("Geometric Area Rug 5x7", "Ruggable", 199, 159,
                       "Washable geometric area rug that anchors living or dining spaces.",
                       "rug,carpet,decor,home"),
                    _p("Gallery Photo Frame Set", "Umbra", 39, 29,
                       "Multi-frame gallery set for creating a personalized photo wall.",
                       "frame,photo,decor,wall"),
                    _p("Faux Plant Set of 3", "Nearly Natural", 59, 45,
                       "Lifelike artificial plants for shelves and desks with no watering needed.",
                       "plant,artificial,decor,home"),
                    _p("Round Gold Wall Mirror", "West Elm", 129, 99,
                       "Round wall mirror with gold-tone frame to brighten any room.",
                       "mirror,wall,decor,gold"),
                    _p("Silent Sweep Wall Clock", "Umbra", 35, 25,
                       "Minimal wall clock with silent sweep movement and no ticking noise.",
                       "clock,wall,decor,home"),
                    _p("Sheer Curtain Pair White", "IKEA", 49, 39,
                       "Light-filtering sheer curtains that soften daylight beautifully.",
                       "curtain,sheer,decor,window"),
                    _p("Linen Table Runner Natural", "Pottery Barn", 39, 29,
                       "Natural linen table runner for dining tables and console styling.",
                       "tablerunner,linen,decor,dining"),
                    _p("Marble Decorative Tray", "West Elm", 69, 55,
                       "Marble tray for organizing perfume, jewelry or coffee-table accents.",
                       "tray,marble,decor,home"),
                ],
            },
            {
                "name": "Lighting",
                "products": [
                    _p("Philips Smart LED Bulb Pack", "Philips", 59, 45,
                       "Smart LED bulb pack with app control for color and brightness.",
                       "lightbulb,led,smart,lighting"),
                    _p("IKEA Floor Lamp Arc", "IKEA", 129, 99,
                       "Arc floor lamp that curves over sofas for stylish reading light.",
                       "floorlamp,lamp,lighting,ikea"),
                    _p("West Elm Pendant Light Glass", "West Elm", 149, 119,
                       "Glass pendant light fixture for kitchen islands and dining areas.",
                       "pendant,light,lighting,glass"),
                    _p("BenQ Desk Lamp USB", "BenQ", 89, 69,
                       "Eye-care desk lamp with USB charging port and adjustable brightness.",
                       "desklamp,lamp,lighting,office"),
                    _p("Hunter Ceiling Fan with LED", "Hunter", 299, 249,
                       "Ceiling fan with integrated LED light for year-round comfort.",
                       "ceilingfan,fan,lighting,home"),
                    _p("Govee RGB Strip Light 16ft", "Govee", 39, 29,
                       "App-controlled RGB LED strip lights for gaming rooms and accents.",
                       "ledstrip,rgb,lighting,smart"),
                    _p("IKEA Bedside Lamp Soft", "IKEA", 29, 22,
                       "Soft-glow bedside lamp with fabric shade for calm night lighting.",
                       "bedsidelamp,lamp,lighting,bedroom"),
                    _p("Solar Outdoor Lantern Set", "Hampton Bay", 49, 39,
                       "Solar-powered outdoor lanterns for patios and garden pathways.",
                       "lantern,outdoor,solar,lighting"),
                    _p("Crystal Mini Chandelier", "Progress Lighting", 199, 159,
                       "Mini chandelier with crystal accents for entryways and dining nooks.",
                       "chandelier,lighting,crystal,home"),
                    _p("Motion Night Light Plug-In", "GE", 19, 14,
                       "Plug-in night light with motion sensor for hallways and bathrooms.",
                       "nightlight,lighting,motion,home"),
                    _p("Neewer Studio Softbox Light", "Neewer", 79, 59,
                       "Softbox studio light kit for content creators and product photos.",
                       "softbox,studio,lighting,photography"),
                    _p("Wall Sconce Pair Brass", "West Elm", 129, 99,
                       "Pair of brass wall sconces for hallway or bedroom ambient light.",
                       "sconce,wall,lighting,brass"),
                ],
            },
            {
                "name": "Storage",
                "products": [
                    _p("SpaceSaver Vacuum Storage Bags", "SpaceSaver", 29, 19,
                       "Vacuum storage bags that compress seasonal clothes and bedding.",
                       "storage,vacuum,bags,organization"),
                    _p("Sterilite Plastic Drawer Tower", "Sterilite", 59, 45,
                       "Multi-drawer plastic tower for closets, dorms and craft rooms.",
                       "drawer,storage,plastic,organization"),
                    _p("Underbed Storage Box Set", "IKEA", 39, 29,
                       "Low-profile underbed boxes for shoes, linens and off-season items.",
                       "storage,underbed,box,organization"),
                    _p("SimpleHouseware Kitchen Rack", "SimpleHouseware", 35, 25,
                       "Kitchen organizer rack for spices, lids and pantry essentials.",
                       "organizer,kitchen,storage,rack"),
                    _p("Closet Hanging Shelves", "Honey-Can-Do", 29, 22,
                       "Hanging closet shelves that add instant vertical storage.",
                       "closet,shelves,storage,organization"),
                    _p("Craftsman Tool Box Steel", "Craftsman", 89, 69,
                       "Steel tool box with tray for garage and DIY project organization.",
                       "toolbox,storage,steel,garage"),
                    _p("Umbra Jewelry Box Velvet", "Umbra", 45, 35,
                       "Velvet-lined jewelry box with compartments for rings and necklaces.",
                       "jewelrybox,storage,velvet,organization"),
                    _p("IRIS File Cabinet Mobile", "IRIS", 69, 55,
                       "Mobile file cabinet on casters for home-office document storage.",
                       "filecabinet,storage,office,organization"),
                    _p("Spice Jar Set 12 Glass", "Kamenstein", 29, 22,
                       "Twelve glass spice jars with labels for a tidy spice drawer.",
                       "spicejar,kitchen,storage,glass"),
                    _p("simplehuman Laundry Basket XL", "simplehuman", 49, 39,
                       "Extra-large laundry basket with dual compartments for sorting.",
                       "laundry,basket,storage,home"),
                    _p("D-Line Cable Management Box", "D-Line", 25, 18,
                       "Cable management box that hides power strips and messy cords.",
                       "cable,management,storage,desk"),
                    _p("OXO Pantry Bin Set", "OXO", 49, 39,
                       "Airtight pantry bins for cereal, flour, snacks and dry goods.",
                       "pantry,bin,storage,kitchen"),
                ],
            },
        ],
    },
    {
        "name": "Beauty",
        "icon": "bx-spa",
        "folder": "beauty",
        "promo_title": "Beauty Essentials",
        "promo_text": "Skincare, hair care, perfume, makeup and men's grooming.",
        "description": "Shop skincare, hair care, perfume, makeup and men's grooming.",
        "subs": [
            {
                "name": "Skincare",
                "products": [
                    _p("The Ordinary Vitamin C Serum 20%", "The Ordinary", 25, 19,
                       "Brightening vitamin C serum that targets dullness and uneven tone.",
                       "skincare,serum,vitaminc,bottle"),
                    _p("CeraVe Hydrating Face Cream", "CeraVe", 22, 16,
                       "Dermatologist-recommended face cream with ceramides and hyaluronic acid.",
                       "skincare,moisturizer,cream,cerave"),
                    _p("Paula's Choice Retinol Night Serum", "Paula's Choice", 54, 44,
                       "Retinol night serum that supports smoother, younger-looking skin.",
                       "skincare,retinol,serum,bottle"),
                    _p("La Roche-Posay SPF 50 Sunscreen", "La Roche-Posay", 36, 28,
                       "Broad-spectrum SPF 50 sunscreen for daily UV protection.",
                       "sunscreen,skincare,spf,bottle"),
                    _p("The Inkey List Niacinamide Toner", "The Inkey List", 18, 14,
                       "Niacinamide toner that helps minimize pores and refine texture.",
                       "toner,skincare,niacinamide,bottle"),
                    _p("Aztec Clay Mask Detox", "Aztec Secret", 12, 9,
                       "Bentonite clay mask for deep cleansing and oil control.",
                       "claymask,skincare,mask,beauty"),
                    _p("Neutrogena Hydro Boost Moisturizer", "Neutrogena", 24, 18,
                       "Oil-free gel moisturizer with hyaluronic acid for thirsty skin.",
                       "moisturizer,skincare,hydroboost,cream"),
                    _p("Good Molecules AHA Exfoliating Lotion", "Good Molecules", 14, 11,
                       "Gentle AHA lotion that exfoliates for smoother, brighter skin.",
                       "exfoliant,skincare,aha,bottle"),
                    _p("The Ordinary Caffeine Eye Serum", "The Ordinary", 12, 9,
                       "Caffeine eye serum that targets puffiness around the eyes.",
                       "eyecream,skincare,serum,beauty"),
                    _p("CeraVe Gentle Foaming Cleanser", "CeraVe", 16, 12,
                       "Gentle foaming facial cleanser that removes dirt without stripping.",
                       "cleanser,skincare,facewash,cerave"),
                    _p("COSRX Sheet Mask Pack 10", "COSRX", 22, 16,
                       "Ten-pack Korean sheet masks for intensive weekly hydration.",
                       "sheetmask,skincare,mask,kbeauty"),
                    _p("Burt's Bees Lip Balm SPF Bundle", "Burt's Bees", 14, 10,
                       "Moisturizing lip balm bundle with SPF for soft, protected lips.",
                       "lipbalm,skincare,burtsbees,beauty"),
                ],
            },
            {
                "name": "Hair Care",
                "products": [
                    _p("Olaplex No.3 Hair Perfector", "Olaplex", 30, 24,
                       "At-home Olaplex treatment that helps repair and strengthen damaged hair.",
                       "haircare,olaplex,treatment,bottle"),
                    _p("Moroccanoil Argan Hair Oil", "Moroccanoil", 48, 38,
                       "Iconic argan oil for shine, frizz control and silky soft hair.",
                       "hairoil,argan,moroccanoil,haircare"),
                    _p("Redken All Soft Conditioner", "Redken", 32, 24,
                       "Deep conditioning formula for dry, brittle hair needing softness.",
                       "conditioner,haircare,redken,bottle"),
                    _p("Olaplex No.8 Hair Mask", "Olaplex", 30, 24,
                       "Moisture mask that leaves hair feeling stronger and smoother.",
                       "hairmask,olaplex,haircare,treatment"),
                    _p("Head & Shoulders Clinical Care", "Head & Shoulders", 14, 10,
                       "Anti-dandruff shampoo that targets itch and flakes effectively.",
                       "shampoo,dandruff,haircare,bottle"),
                    _p("TRESemmé Heat Protect Spray", "TRESemmé", 12, 9,
                       "Heat protectant spray for blow-drying, straightening and curling.",
                       "hairspray,heatprotect,haircare,bottle"),
                    _p("Gisou Honey Infused Hair Serum", "Gisou", 52, 42,
                       "Honey-infused hair serum for glossy, frizz-free finish.",
                       "hairserum,gisou,haircare,bottle"),
                    _p("Briogeo Scalp Revival Scrub", "Briogeo", 42, 34,
                       "Charcoal scalp scrub that detoxes buildup for healthier roots.",
                       "scalp,scrub,haircare,briogeo"),
                    _p("It's a 10 Leave-In Conditioner", "It's a 10", 28, 22,
                       "Multi-benefit leave-in conditioner for detangling and shine.",
                       "leavein,conditioner,haircare,bottle"),
                    _p("Dyson Supersonic Hair Dryer", "Dyson", 429, 399,
                       "Dyson Supersonic hair dryer with intelligent heat control.",
                       "hairdryer,dyson,haircare,tool"),
                    _p("GHD Platinum+ Straightener", "ghd", 309, 279,
                       "Professional straightener with predictive technology for less damage.",
                       "straightener,ghd,haircare,tool"),
                    _p("Ouidad Curl Defining Cream", "Ouidad", 28, 22,
                       "Curl cream that defines coils and reduces frizz without crunch.",
                       "curlcream,ouidad,haircare,curly"),
                ],
            },
            {
                "name": "Perfume",
                "products": [
                    _p("Chanel Coco Mademoiselle EDP", "Chanel", 148, 129,
                       "Iconic Chanel eau de parfum with fresh oriental floral notes.",
                       "perfume,chanel,fragrance,bottle"),
                    _p("Dior Sauvage EDT", "Dior", 128, 109,
                       "Fresh spicy Dior Sauvage eau de toilette — modern masculine classic.",
                       "perfume,dior,sauvage,fragrance"),
                    _p("Tom Ford Oud Wood EDP", "Tom Ford", 280, 249,
                       "Luxurious Tom Ford Oud Wood with rich woody oriental character.",
                       "perfume,tomford,oud,fragrance"),
                    _p("YSL Black Opium EDP", "Yves Saint Laurent", 138, 118,
                       "Addictive Black Opium scent with coffee and vanilla facets.",
                       "perfume,ysl,blackopium,fragrance"),
                    _p("Bleu de Chanel EDP", "Chanel", 148, 129,
                       "Fresh aromatic woody fragrance for everyday sophistication.",
                       "perfume,chanel,bleu,fragrance"),
                    _p("Viktor & Rolf Flowerbomb", "Viktor & Rolf", 145, 125,
                       "Explosive floral perfume with patchouli warmth and sweet petals.",
                       "perfume,flowerbomb,fragrance,bottle"),
                    _p("Acqua di Gio Profondo", "Giorgio Armani", 128, 108,
                       "Aquatic aromatic fragrance inspired by Mediterranean freshness.",
                       "perfume,armani,acquadigio,fragrance"),
                    _p("Jo Malone Peony & Blush Suede", "Jo Malone", 158, 138,
                       "Soft peony and blush suede cologne for elegant daytime wear.",
                       "perfume,jomalone,floral,fragrance"),
                    _p("Versace Dylan Blue EDT", "Versace", 98, 79,
                       "Fresh aromatic fougere with aquatic and woody depth.",
                       "perfume,versace,dylanblue,fragrance"),
                    _p("Lancôme La Vie Est Belle", "Lancôme", 132, 112,
                       "Gourmand iris fragrance celebrating joy and femininity.",
                       "perfume,lancome,fragrance,bottle"),
                    _p("Armaf Club de Nuit Intense", "Armaf", 49, 39,
                       "Bold fruity-smoky cologne popular for confident everyday wear.",
                       "perfume,cologne,fragrance,bottle"),
                    _p("Travel Perfume Atomizer Trio", "Travalo", 29, 22,
                       "Refillable travel atomizer trio for carrying favorite scents.",
                       "perfume,travel,atomizer,fragrance"),
                ],
            },
            {
                "name": "Makeup",
                "products": [
                    _p("Maybelline SuperStay Matte Lipstick", "Maybelline", 12, 9,
                       "Long-wear matte liquid lipstick that stays put through the day.",
                       "lipstick,makeup,maybelline,beauty"),
                    _p("Fenty Beauty Pro Filt'r Foundation", "Fenty Beauty", 42, 34,
                       "Soft matte foundation with inclusive shade range and buildable cover.",
                       "foundation,makeup,fenty,beauty"),
                    _p("Lakme Eyeconic Kajal", "Lakme", 8, 6,
                       "Smudge-proof kajal pencil for defined, dramatic eyes.",
                       "kajal,eyeliner,makeup,lakme"),
                    _p("Rare Beauty Soft Pinch Blush", "Rare Beauty", 26, 20,
                       "Weightless liquid blush that blends to a natural healthy flush.",
                       "blush,makeup,rarebeauty,beauty"),
                    _p("Maybelline Lash Sensational Mascara", "Maybelline", 12, 9,
                       "Volumizing mascara that fans lashes for a full, lifted look.",
                       "mascara,makeup,maybelline,beauty"),
                    _p("Urban Decay Naked Eyeshadow Palette", "Urban Decay", 54, 44,
                       "Versatile nude eyeshadow palette for day-to-night looks.",
                       "eyeshadow,palette,makeup,urbandecay"),
                    _p("NARS Radiant Creamy Concealer", "NARS", 32, 26,
                       "Creamy concealer that brightens under-eyes with medium coverage.",
                       "concealer,makeup,nars,beauty"),
                    _p("MAC Prep + Prime Fix+ Spray", "MAC", 32, 26,
                       "Setting and finishing spray that refreshes makeup and skin.",
                       "settingspray,makeup,mac,beauty"),
                    _p("Rare Beauty Positive Light Highlighter", "Rare Beauty", 26, 20,
                       "Cream highlighter stick for an instant lit-from-within glow.",
                       "highlighter,makeup,rarebeauty,beauty"),
                    _p("Anastasia Brow Wiz Pencil", "Anastasia Beverly Hills", 26, 20,
                       "Ultra-fine brow pencil for hair-like strokes and natural shape.",
                       "brow,pencil,makeup,anastasia"),
                    _p("Essie Nail Lacquer Set 6", "Essie", 36, 28,
                       "Six-piece Essie nail lacquer set in wearable everyday shades.",
                       "nailpolish,essie,makeup,beauty"),
                    _p("Real Techniques Brush Kit 12", "Real Techniques", 32, 24,
                       "12-piece makeup brush kit for face, eyes and seamless blending.",
                       "brushes,makeup,kit,beauty"),
                ],
            },
            {
                "name": "Men Grooming",
                "products": [
                    _p("Beardbrand Beard Oil Utility", "Beardbrand", 28, 22,
                       "Conditioning beard oil that softens whiskers and nourishes skin.",
                       "beardoil,grooming,men,beard"),
                    _p("Philips Norelco Multigroom Kit", "Philips", 49, 39,
                       "All-in-one trimmer kit for beard, hair and detailed grooming.",
                       "trimmer,philips,grooming,men"),
                    _p("Harry's Face Wash Charcoal", "Harry's", 12, 9,
                       "Charcoal face wash that cleanses without over-drying men's skin.",
                       "facewash,harrys,grooming,men"),
                    _p("Kiehl's Facial Fuel Aftershave", "Kiehl's", 32, 26,
                       "Soothing aftershave balm that calms razor burn and hydrates.",
                       "aftershave,kiehls,grooming,men"),
                    _p("American Crew Fiber Pomade", "American Crew", 22, 16,
                       "High-hold pomade with matte finish for textured men's styles.",
                       "pomade,americancrew,grooming,hair"),
                    _p("Dove Men+Care Body Wash", "Dove", 10, 7,
                       "Hydrating men's body wash that cleanses without stripping moisture.",
                       "bodywash,dove,grooming,men"),
                    _p("Old Spice Deodorant Twin Pack", "Old Spice", 12, 9,
                       "Long-lasting deodorant twin pack with classic fresh scent.",
                       "deodorant,oldspice,grooming,men"),
                    _p("Harry's Foaming Shave Gel", "Harry's", 10, 7,
                       "Rich foaming shave gel for a smooth, comfortable razor glide.",
                       "shaving,gel,harrys,grooming"),
                    _p("ManScaped Grooming Kit Travel", "ManScaped", 79, 59,
                       "Travel grooming kit with trimmer and essentials for on-the-go care.",
                       "groomingkit,manscaped,men,travel"),
                    _p("Clinique For Men Moisturizer SPF", "Clinique", 36, 28,
                       "Lightweight men's moisturizer with SPF for daily face protection.",
                       "moisturizer,clinique,grooming,men"),
                    _p("Philips Nose Hair Trimmer", "Philips", 19, 14,
                       "Precision nose and ear hair trimmer with washable heads.",
                       "trimmer,nose,philips,grooming"),
                    _p("Just For Men Hair Color Natural Black", "Just For Men", 14, 10,
                       "Easy men's hair color that blends gray for a natural black look.",
                       "haircolor,justformen,grooming,men"),
                ],
            },
        ],
    },
]


CATEGORY_IMAGE_TAGS = {
    "Electronics": "electronics,gadgets,technology",
    "Fashion": "fashion,clothing,style",
    "Home & Kitchen": "home,kitchen,interior",
    "Beauty": "beauty,cosmetics,skincare",
}


# Old category names to deactivate/clear when reseeding
LEGACY_CATEGORY_NAMES = [
    "Beauty & Personal Care",
]


def long_description(product: dict, category_name: str, sub_name: str) -> str:
    title = product["title"]
    brand = product["brand"]
    short = product["short"]
    return (
        f"<p><strong>{title}</strong> by <strong>{brand}</strong> — {short}</p>"
        f"<p>This genuine {brand} product is listed under {category_name} → {sub_name} "
        f"and is curated so the listing matches the product you see.</p>"
        f"<ul>"
        f"<li>Brand: {brand}</li>"
        f"<li>Category: {category_name}</li>"
        f"<li>Subcategory: {sub_name}</li>"
        f"<li>Authentic matched product details</li>"
        f"<li>Fast shipping and easy returns on Shopingo</li>"
        f"</ul>"
    )
